### ISSUE TITLE
회사 사이트의 '소개' 및 '서비스' 페이지 디자인 변경

### ISSUE THREAD

**Issue by tpdud406** [knowease-inc/knowease-inc.github.io#192]
# :sparkles: Feature Request

## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.

 - 최신 디자인 트렌드를 반영해 회사 사이트의 '소개' 및 '서비스' 페이지에 전문적이고 현대적인 분위기 강조
 - 사용자 경험을 개선해 사이트의 신뢰성과 가독성을 높이고, 방문자에게 긍정적인 첫인상을 제공

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.

 - 현재 '소개' 및 '서비스' 페이지는 최신 디자인 트렌드와 다소 거리가 있어, 회사의 전문성과 혁신성을 충분히 전달하지 못함
 
## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.

 - @tpdud406 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.

  - [x] 회사 소개 페이지의 Nuxt3 버전업
      - [x] MEANIIT-frontend 리포지토리의 Nuxt3와 node 버전 맞추기
  - [x] 언어 전환 (Kor, Eng) 
      - [x] 버튼 생성
      - [x] 버튼 클릭시 전환 로직 추가
  - [x] 디자인 변경
      - [x] [소개 페이지]
         - [x] 큰 골격 생성 (이미지, 텍스트 들어갈 위치, 화면 구성 등) _ 배경이 컨텐츠 프레임보다 더 넓은 영역 차지
         - [x] 첫 노출 이미지(화면 전체 차지) 및 비전 텍스트
         - [x] App-bar 구성 변경 (좌측에 로고, 기타 메뉴 우측 정렬 / 모바일은 햄버거 아이콘)
      - [x] [서비스 소개 페이지]
         - [x] 큰 골격 생성 (이미지, 텍스트 들어갈 위치, 화면 구성 등) _ 배경이 컨텐츠 프레임보다 더 넓은 영역 차지
         - [x] 첫 노출 이미지(화면 전체 차지) 및 비전 텍스트
         - [x] App-bar 구성 변경 (좌측에 로고, 기타 메뉴 우측 정렬 / 모바일은 햄버거 아이콘)
         - [x] 좌측에 강점 텍스트 + 우측에 서비스 모습(PC 버전)
  - [x] Dark 모드 (옵션)

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우, "#" 혹은 URI 전체를 복사붙여넣기 하는 형태로 **반드시 이슈 번호를 적어주세요**

  - 관련이슈
    - https://github.com/knowease-inc/MEANIIT-frontend/issues/437
  - 참고문서 URL, 스크린샷 등
    - [1차 피드백 작업 완료](https://github.com/knowease-inc/MEANIIT-frontend/issues/437#issuecomment-2492608104)
    - [회사 소개 페이지 구조](https://github.com/knowease-inc/MEANIIT-frontend/issues/437#issuecomment-2493107061)
    - [서비스 소개 페이지 구조](https://github.com/knowease-inc/MEANIIT-frontend/issues/437#issuecomment-2493303790)

    - [피드백1](https://github.com/knowease-inc/MEANIIT-frontend/issues/437#issuecomment-2477997125)
    - [피드백2](https://github.com/knowease-inc/MEANIIT-frontend/issues/437#issuecomment-2478027473)
    - [creattie 관련_이미지, 아이콘 등](https://github.com/knowease-inc/MEANIIT-frontend/issues/437#issuecomment-2478022981)
    - [언어 전환 관련 기록](https://github.com/knowease-inc/MEANIIT-frontend/issues/437#issuecomment-2519073276)

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 한가지만 선택해주세요.
> (1W+ 가 아닌 경우 레이블을 변경해주세요.)

  - 예상소요시간: :blue_car: **1W+**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain, Priority, Task를 **각각 한가지만** 선택해주세요.
> (UX, Medium, Enhancement 가 아닌 경우 레이블을 변경해주세요.)

  - Reporter: @T-Mook 
  - Domain  : :briefcase: **Business**
  - Priority: :orange_square: **High**
  - Task    : :memo: **Documentation**

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.

  - 예상수익: :dollar: (원/월) TBD
  - 예상비용: :money_with_wings: (원/월) TBD

**Comment by tpdud406** [comment]
@T-Mook 

- Nuxt3로 마이그래이션 중에 아래와 같은 에러가 발생해서 확인중입니다..
- 기초 설정 값들 변경하고 실행했을땐 문제가 없었는데 어제부터 갑자기(?) `ERROR  [unhandledRejection] EMFILE: too many open files` 가 발생하더니 정상 실행이 안되고 있습니다. 
   - 현재 Meaniit이랑 같은 모듈들을 저장했는데도 knowease에서만 이 에러가 발생
   - **( 혹시 이 에러에 대해 아시는 것이 있다면.. 코멘트 부탁드립니다..!)**
- 지금 모듈 하나씩 체크해가며 확인중인데, 월요일까지 확인해보고 안되면 일단 패키지 원복 시켜서 디자인 변경 먼저 진행 후 다시 마이그래이션 시도해보려고 합니다..!

```javascript
yarn dev
yarn run v1.22.21
$ nuxt dev
Nuxt 3.13.2 with Nitro 2.9.7                                               12:39:16 PM
                                                                           12:39:16 PM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

  ➜ DevTools: press Shift + Option + D in the browser (v1.6.0)             12:39:17 PM


[12:39:18 PM]  ERROR  [unhandledRejection] EMFILE: too many open files, watch '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/@nuxtjs/vuetify/node_modules/vuetify/es5/locale/en.js.map'

  at __node_internal_captureLargerStackTrace (node:internal/errors:497:5)
  at __node_internal_uvException (node:internal/errors:553:10)
  at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
  at watch (node:fs:2392:36)
  at createFsWatchInstance (node_modules/unstorage/node_modules/chokidar/src/handler.ts:163:12)
  at setFsWatchListener (node_modules/unstorage/node_modules/chokidar/src/handler.ts:228:15)
  at NodeFsHandler._watchWithNodeFs (node_modules/unstorage/node_modules/chokidar/src/handler.ts:398:16)
  at NodeFsHandler._handleFile (node_modules/unstorage/node_modules/chokidar/src/handler.ts:460:25)
  at NodeFsHandler._addToNodeFs (node_modules/unstorage/node_modules/chokidar/src/handler.ts:735:23)


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/revive-payload.client.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/revive-payload.client.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/revive-payload.server.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/revive-payload.server.js'


[12:39:18 PM]  ERROR  EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/.nuxt/tsconfig.json'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/chunk-reload.client.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/revive-payload.client.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/revive-payload.client.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/head/runtime/plugins/unhead.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/head/runtime/plugins/unhead.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/head/runtime/plugins/unhead.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/head/runtime/plugins/unhead.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/chunk-reload.client.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/pages/runtime/plugins/router.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/pages/runtime/plugins/router.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/pages/runtime/plugins/router.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/pages/runtime/plugins/router.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/head/runtime/plugins/unhead.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/head/runtime/plugins/unhead.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/pages/runtime/plugins/router.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/pages/runtime/plugins/router.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/dev-server-logs.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/dev-server-logs.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/check-if-layout-used.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/dev-server-logs.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/dev-server-logs.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/check-if-layout-used.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/dev-server-logs.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/dev-server-logs.js'


[12:39:18 PM]  WARN  Failed to parse static properties from plugin node_modules/nuxt/dist/app/plugins/check-if-layout-used.js. EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js'


[12:39:18 PM]  ERROR  Cannot start nuxt:  EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/.nuxt/types/app.config.d.ts'

  at Object.open (node:internal/fs/sync:78:18)
  at Object.openSync (node:fs:565:17)
  at writeFileSync (node:fs:2288:35)
  at node_modules/nuxt/dist/index.mjs:5294:9
  at generateApp (node_modules/nuxt/dist/index.mjs:5301:5)
  at async _applyPromised (node_modules/perfect-debounce/dist/index.mjs:54:10)


[12:39:18 PM]  ERROR  [unhandledRejection] EMFILE: too many open files, open '/Users/geta/Desktop/get-A/knowease-inc.github.io/.nuxt/types/app.config.d.ts'

  at Object.open (node:internal/fs/sync:78:18)
  at Object.openSync (node:fs:565:17)
  at writeFileSync (node:fs:2288:35)
  at node_modules/nuxt/dist/index.mjs:5294:9
  at generateApp (node_modules/nuxt/dist/index.mjs:5301:5)
  at async _applyPromised (node_modules/perfect-debounce/dist/index.mjs:54:10)


[12:39:18 PM]  ERROR  [uncaughtException] EMFILE: too many open files, scandir '/Users/geta/Desktop/get-A/knowease-inc.github.io'
```

**Comment by T-Mook** [comment]
@tpdud406 

- 저도 아직 아는 바는 업는 에러이지만,

> 안되면 일단 패키지 원복 시켜서 디자인 변경 먼저 진행 후 다시 마이그래이션 시도해보려고 합니다..!

- 마이그레이션을 우선하시는게 작업이 더 편하실거에요. 했던 코드 또 세부수정 해야하는게 멘탈에 더 안 좋습니다 ㅎㅎ

> 현재 Meaniit이랑 같은 모듈들을 저장했는데도 knowease에서만 이 에러가 발생

- 혹시나 해서 드리는 말씀이지만,
   1. Nuxt3, Vuetify와 같은 (디자인)프레임워크 버전 정도만 일치시켜주시면 됩니다. **이외 다른 모듈을 동일하게 설치하실 필요 없습니다.**
   2. 이외 모듈은 꼭 필요해서 쓰는 것이 아니면 아예 사용하지 않아도 됩니다. 달리 말하면 프레임워크만 설치된 **완전히 제로인 상태에서 에러가 나지 않는다면, 그 상태에서 디자인 추가**하시면서 작업하시면 됩니다

**Comment by tpdud406** [comment]
[참고]

- https://github.com/nuxt/nuxt/issues/29744

- 이 이슈에 해당하는 오류로 예상됨..

**Comment by tpdud406** [comment]
저도 gpt한테 물어봤는데

1. 파일 수를 조정하는 것은 근본적인 해결책이 아닌 것 같아 '파일 제한 수'를 조정하진 않았습니다! (Meaniit은 괜찮은데 이 프로젝트만 문제라..)
2. 2번, 3번은 해봤는데 해결이 안됐습니다...ㅠㅠ

**Comment by tpdud406** [comment]
@T-Mook 

- 큰 골격만 잡아서 커밋 올렸습니다!
- 서비스 소개 페이지에서 동영상 파일은 https://github.com/knowease-inc/MEANIIT-frontend/issues/437#issuecomment-2476172920 에 첨부했습니다!

**Comment by T-Mook** [comment]
## 버전 기록
- node `20.9.0`

**Comment by tpdud406** [comment]
@T-Mook 
### 확인 부탁드립니다!


### 참고사항
- **UI/UX 조사 및 멘트 확정 후 UI/UX 및 레이아웃 재조정 필요 (+ 이미지 확정 필요)**
- **이미지(동영상) 배경**은 기본 하얀색이라 **다크모드시엔 반전**되게 했는데, 실제 데이터 다운로드 후 배경색 존재 여부 확인 후 **조정 필요**
- **영어**(`en.json`) 파일 내에 텍스트는 기존 텍스트를 **임시로 번역**해놓았습니다!

**Comment by tpdud406** [comment]
@T-Mook 
- 레이아웃 검토 후 PR 올려두었습니다!
- 피드백 부탁드립니다~
